#!/usr/bin/env python3

import sys
import argparse
import trimesh
import math
import stl
from pathlib import Path

# stlinfo_path = '/Users/yumenghe/stlinfo/'
# sys.path.append(stlinfo_path)

from stlinfo import STLFile

# adopt code from stilinfo
# scale the model to fit the build plate
def to_stl(file):
    p = Path(file)
    if p.suffix == ".3mf":
        np = p.with_suffix(".stl")
        for m in stl.Mesh.from_3mf_file(p):
            m.save(np)
        return np
    elif p.suffix == ".stl":
        return p
    else:
        raise NotImplementedError("Only support stl/3mf file format")

def do_compute(args):
    f = STLFile()
    f.load_file(args.file)
    minp, maxp = f.bounds()
    x, y, z = tuple([float(b) for b in args.volume.split(",")])
    
    if not f.fits((minp, maxp), x, y, z, rot=False):  # need to scale the mesh
        px = maxp.x - minp.x + 1
        py = maxp.y - minp.y + 1
        pz = maxp.z - minp.z + 1
        
        scale = math.ceil(max([px / x, py / y, pz / z]))
        return 1 / scale
    else:
        return 1
    
def do_scale(args):
    mesh = trimesh.load(args.file)
    
    if args.factor != 1:
        mesh.apply_scale(args.factor)
        
    if args.output is not None:
        mesh.export(args.output)
    else:
        p = Path(args.file)
        mesh.export(p.with_stem(f"{p.stem}_scaled_{args.factor}"))
    

if __name__ == "__main__":
    p = argparse.ArgumentParser(description="Scale stl/3mf file")
    
    p.add_argument("file", type=to_stl)
    
    sp = p.add_subparsers(dest="cmd")
    
    sf = sp.add_parser("compute", help="calculate scaling factor")
    sf.add_argument("--volume", "-v", default="300,300,250", help="Build volume in the format of x,y,z")
    
    ss = sp.add_parser("scale", help="scale file")
    ss.add_argument("factor", type=float, help="scaling factor")
    ss.add_argument("-o", "--output", help="directory to store the scaled mesh")
    
    args = p.parse_args()
    
    if args.cmd == "compute":
        sys.exit(do_compute(args))
    elif args.cmd == "scale":
        sys.exit(do_scale(args))
   
   